# -*- coding: utf-8 -*-
"""MlProject-Predicting Asthma Using Machine Learning Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ezBlR8IoSyw1AELggDfPOxrqCN7Z3ab

#Predicting Asthma Using Machine Learning Models

## Group Members
- Simintaj Salehpour
- Jeongwon Yoo
- Ebrima Sissoko

## Course Information
Data Science Program  
George Washington University  

Instructor: Yuxiao Huang  

## Project Overview
This project aims to develop and evaluate machine learning models to predict asthma status.
The pipeline includes data preprocessing, feature selection, model training,
hyperparameter tuning, and performance evaluation.

## Table of Contents

- [1. Overview](#1-overview)
- [2. Exploratory Data Analysis](#2-exploratory-data-analysis)
- [3. Data Preprocessing](#3-data-preprocessing)
- [4. Model Training](#4-model-training)
- [5. Hyperparameter Tuning](#5-hyperparameter-tuning)
- [6. Model Evaluation](#6-model-evaluation)
- [7. Interpretation](#7-interpretation)
- [8. Conclusion](#8-conclusion)

## 1. Overview

- This notebook presents a machine learning pipeline for predicting asthma status.
- The workflow includes data preprocessing, feature selection, model training, and evaluation.
- Multiple models are compared to identify the best-performing approach.
- Special attention is given to handling class imbalance and improving F1-macro score.
- The final goal is to build a robust and generalizable classification model.

**Mount Google Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Warning**"""

import warnings

# Ignore warnings
warnings.filterwarnings('ignore')

"""**Install Packages**"""

pip install xgboost imbalanced-learn catboost lightgbm tensorflow catboost

"""**Import Libraries**"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV, PredefinedSplit
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.utils.class_weight import compute_sample_weight, compute_class_weight

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from imblearn.over_sampling import SMOTE

import matplotlib.pyplot as plt

# Set default figure size and other parameters for better plot readability
plt.rcParams['figure.figsize'] = (10, 7)  # Adjust width and height as needed
plt.rcParams['font.size'] = 12            # Default font size for text elements
plt.rcParams['axes.titlesize'] = 14       # Font size for plot titles
plt.rcParams['axes.labelsize'] = 12       # Font size for x and y labels
plt.rcParams['xtick.labelsize'] = 10      # Font size for x-axis ticks
plt.rcParams['ytick.labelsize'] = 10      # Font size for y-axis ticks
plt.rcParams['legend.fontsize'] = 10      # Font size for legends
plt.rcParams['figure.dpi'] = 100          # Dots per inch for plot resolution

"""**Define Random Seed**"""

# The random seed
random_seed = 42

# Set random seed in tensorflow
tf.random.set_seed(random_seed)

# Set random seed in numpy
np.random.seed(random_seed)

"""**Set the dataset path and read the data**"""

abspath_curr = "/content/drive/MyDrive/Colab Notebooks/teaching/gwu/machine_learning_I/Project"
file_path=abspath_curr + "/Dataset/brfss_2020_2024_pooled_ml.parquet"
df=pd.read_parquet(file_path)

"""**Quick check: Dataset information**"""

print("\nDataset size:\n")
print(df.shape)
print("\nDataset Information:\n")
print(df.info())
print("\n The first 5 rows of dataset:\n")
print(df.head().to_string())
print("Data set columns names:",df.columns)

"""# Exploratory Data Analysis (EDA)
**Team Target: Asthma**

Target Variable Distribution
"""

import seaborn as sns
import matplotlib.ticker as mticker

targets = {
    "ASTHNOW": "Asthma (Current)"
}

# Create a single subplot for the asthma distribution
fig, ax = plt.subplots(1, 1, figsize=(8, 6))

for col, title in targets.items():
    if col in df.columns:
        counts = df[col].value_counts(dropna=False).sort_index()
        colors = ['#2ecc71', '#e74c3c', '#3498db', '#f39c12', '#9b59b6'][:len(counts)]

        # Map original values to descriptive labels
        x_labels = {1.0: 'Yes', 2.0: 'No', np.nan: 'Missing'}
        mapped_x_labels = [x_labels.get(val, str(val)) for val in counts.index]

        ax.bar(mapped_x_labels, counts.values, color=colors)
        ax.set_title(title, fontsize=16)
        ax.set_xlabel("Asthma Status") # Updated x-axis label
        ax.set_ylabel("Count")

        # Format y-axis to show counts in 500k intervals
        formatter = mticker.StrMethodFormatter('{x:,.0f}') # Format as integer with comma
        ax.yaxis.set_major_formatter(formatter)
        ax.yaxis.set_major_locator(mticker.MultipleLocator(500000)) # Set major ticks at 500k intervals

        total = counts.sum()
        for i, (val, count) in enumerate(counts.items()):
            ax.text(i, count + total * 0.01, f"{count / total * 100:.1f}%",
                           ha='center', fontsize=11)
    else:
        ax.text(0.5, 0.5, f"{col}\nnot found", ha='center', va='center', fontsize=14)
        ax.set_title(title)

plt.suptitle("Target Variable Distribution", fontsize=18, y=1.02)
plt.tight_layout()
plt.show()

"""Asthma Status vs Key Risk Factors"""

if 'ASTHNOW' in df.columns:
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    asthma_clean = df[df['ASTHNOW'].isin([1.0, 2.0])].copy() # Filter for Yes (1.0) and No (2.0)
    asthma_clean['Asthma_Status'] = asthma_clean['ASTHNOW'].map({
        1.0: 'Yes', 2.0: 'No'
    })

    order = ['Yes', 'No']
    colors = ['#e74c3c', '#2ecc71'] # Red for Yes, Green for No

    # Age group mapping based on common BRFSS coding (adjust if actual codes differ)
    age_group_labels = {
        1: '18-24',
        2: '25-29',
        3: '30-34',
        4: '35-39',
        5: '40-44',
        6: '45-49',
        7: '50-54',
        8: '55-59',
        9: '60-64',
        10: '65-69',
        11: '70-74',
        12: '75-79',
        13: '80+',
        14: 'Missing/DK'
    }

    # 1. By Age Group
    if '_AGEG5YR' in df.columns:
        ct = pd.crosstab(asthma_clean['_AGEG5YR'],
                         asthma_clean['Asthma_Status'])
        if all(c in ct.columns for c in order):
            ct[order].plot(kind='bar', stacked=True, ax=axes[0, 0], color=colors)

        # Map existing numerical labels to descriptive age ranges
        current_ticks = ct.index.tolist()
        mapped_labels = [age_group_labels.get(int(t), str(t)) for t in current_ticks]

        axes[0, 0].set_title('Asthma by Age Group')
        axes[0, 0].set_xlabel('Age Group')
        axes[0, 0].set_xticklabels(mapped_labels, rotation=45, ha='right')
        axes[0, 0].legend(fontsize=9)
        axes[0, 0].yaxis.set_major_formatter(mticker.StrMethodFormatter('{x:,.0f}'))

    # 2. By BMI
    if '_BMI5' in df.columns:
        for label, color in zip(order, colors):
            subset = asthma_clean[asthma_clean['Asthma_Status'] == label]['_BMI5'].dropna() / 100
            axes[0, 1].hist(subset, bins=40, alpha=0.5, label=label, color=color, density=False)
        axes[0, 1].set_title('BMI Distribution by Asthma Status')
        axes[0, 1].set_xlabel('BMI')
        axes[0, 1].legend(fontsize=9)
        axes[0, 1].yaxis.set_major_formatter(mticker.StrMethodFormatter('{x:,.0f}'))

    # 3. By General Health
    if 'GENHLTH' in df.columns:
        ct = pd.crosstab(asthma_clean['GENHLTH'],
                         asthma_clean['Asthma_Status'])
        if all(c in ct.columns for c in order):
            ct[order].plot(kind='bar', stacked=True, ax=axes[0, 2], color=colors)
        axes[0, 2].set_title('Asthma by General Health')
        axes[0, 2].set_xticklabels(['Excellent', 'Very Good', 'Good', 'Fair', 'Poor'], rotation=30)
        axes[0, 2].legend(fontsize=9)
        axes[0, 2].yaxis.set_major_formatter(mticker.StrMethodFormatter('{x:,.0f}'))

    # 4. By Exercise
    if 'EXERANY2' in df.columns:
        ct = pd.crosstab(asthma_clean['EXERANY2'],
                         asthma_clean['Asthma_Status'])
        if all(c in ct.columns for c in order):
            ct[order].plot(kind='bar', stacked=True, ax=axes[1, 0], color=colors)
        axes[1, 0].set_title('Asthma by Exercise')
        axes[1, 0].set_xticklabels(['Yes', 'No'], rotation=0)
        axes[1, 0].legend(fontsize=9)
        axes[1, 0].yaxis.set_major_formatter(mticker.StrMethodFormatter('{x:,.0f}'))

    # 5. By Heart Disease (using CVDCRHD4 for Coronary Heart Disease as an example)
    if 'CVDCRHD4' in df.columns:
        ct = pd.crosstab(asthma_clean['CVDCRHD4'],
                         asthma_clean['Asthma_Status'])
        if all(c in ct.columns for c in order):
            ct[order].plot(kind='bar', stacked=True, ax=axes[1, 1], color=colors)
        axes[1, 1].set_title('Asthma by Coronary Heart Disease')
        axes[1, 1].set_xticklabels(['Yes', 'No'], rotation=0)
        axes[1, 1].legend(fontsize=9)
        axes[1, 1].yaxis.set_major_formatter(mticker.StrMethodFormatter('{x:,.0f}'))

    # 6. By Difficulty Walking
    if 'DIFFWALK' in df.columns:
        ct = pd.crosstab(asthma_clean['DIFFWALK'],
                         asthma_clean['Asthma_Status'])
        if all(c in ct.columns for c in order):
            ct[order].plot(kind='bar', stacked=True, ax=axes[1, 2], color=colors)
        axes[1, 2].set_title('Asthma by Difficulty Walking')
        axes[1, 2].set_xticklabels(['Yes', 'No'], rotation=0)
        axes[1, 2].legend(fontsize=9)
        axes[1, 2].yaxis.set_major_formatter(mticker.StrMethodFormatter('{x:,.0f}'))

    plt.suptitle('Asthma Status vs Risk Factors', fontsize=18, y=1.02)
    plt.tight_layout()
    plt.show()

###### END OF EDA------######

"""## 2. Data Preprocessing

### 2.1 Data Cleaning

**Check Duplicates**
"""

print("Dataset shape before cleaning:", df.shape)

# Check duplicates
duplicate_rows = df.duplicated().sum()
print("\nNumber of duplicate rows:", duplicate_rows)

# Remove duplicates
df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

"""### 2.2 Missing Value Analysis"""

missing_percent = (df.isnull().mean() * 100)

high_missing_cols = missing_percent[missing_percent > 40]

print("Number of columns with >40% missing:", len(high_missing_cols))
print(high_missing_cols.sort_values(ascending=False).head(10))

"""### 2.3 Target Cleaning and Encoding

**Check and Clean target:**
*  keep only valid asthma labels (Remove Nan Values)
*   relable the target values:
*  1 = yes, 0 = no
"""

target = "ASTHNOW"
print("Target(Asthma) before cleaning:\n")
print(df[target].value_counts(dropna=False))

# keep only valid classes (removes NaN)
df = df[df[target].notna()].copy()

# Convert to binary
df[target] = df[target].map({1.0: 1, 2.0: 0})

# Remove rows where target is missing
df_model = df[df[target].notna()].copy()

print("Target distribution after removing missing target:")
print(df_model[target].value_counts(dropna=False))

print("\nShape after target cleaning:", df_model.shape)

"""### 2.4 Remove High Missing Features"""

missing_percent_model = (df_model.isnull().sum() / len(df_model)) * 100

high_missing_threshold = 40

high_missing_cols = missing_percent_model[
    (missing_percent_model > high_missing_threshold) &
    (missing_percent_model.index != target)
].index.tolist()

print("Columns with more than", high_missing_threshold, "% missing:")
print(high_missing_cols)

df_model = df_model.drop(columns=high_missing_cols)

print("Shape after dropping high-missing columns:", df_model.shape)

"""### 2.5 Feature and Target Separation"""

X = df_model.drop(columns=[target]).copy()
y = df_model[target].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

"""### 2.6 Remove Leakage Features"""

leakage_cols = [
    "_ASTHMS1",
    "_CASTHM1",
    "CASTHDX2",
    "ASTHMA3",
    "ASTHNOW",
    "ASTHNOW_label"
]

X = X.drop(columns=[col for col in leakage_cols if col in X.columns])

print("Number of features after removing leakage:", X.shape[1])

"""**Encode target**"""

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

print("Target classes:", label_encoder.classes_)
print("Encoded target counts:", np.bincount(y))

"""### 2.7 Train / Validation / Test Split"""

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=random_seed
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=random_seed
)

print("Train shape:", X_train.shape)
print("Validation shape:", X_val.shape)
print("Test shape:", X_test.shape)

"""### 2.8 Missing Value Imputation"""

true_numeric_cols = [
    "CHILDREN", "HEIGHT3", "HTIN4", "HTM4",
    "WEIGHT2", "WTKG3", "_AGE80",
    "_BMI5", "_BMI5_SCALED",
    "MENTHLTH", "PHYSHLTH", "POORHLTH"
]

num_cols = [col for col in true_numeric_cols if col in X_train.columns]
cat_cols = [col for col in X_train.columns if col not in num_cols]

print("Numerical columns:")
print(num_cols)

print("\nCategorical/code columns:")
print(cat_cols)

# Numeric columns: fill with train median
for col in num_cols:
    median_value = X_train[col].median()

    if pd.isna(median_value):
        median_value = -1

    X_train[col] = X_train[col].fillna(median_value)
    X_val[col] = X_val[col].fillna(median_value)
    X_test[col] = X_test[col].fillna(median_value)

# Categorical/code columns: fill with train mode
for col in cat_cols:
    mode_value = X_train[col].mode(dropna=True)

    if len(mode_value) > 0:
        fill_value = mode_value.iloc[0]
    else:
        fill_value = -1

    X_train[col] = X_train[col].fillna(fill_value)
    X_val[col] = X_val[col].fillna(fill_value)
    X_test[col] = X_test[col].fillna(fill_value)

# Convert all columns to float32 after missing values are handled
X_train = X_train.astype("float32")
X_val = X_val.astype("float32")
X_test = X_test.astype("float32")

print("\nMissing values after imputation:")
print("Train:", X_train.isnull().sum().sum())
print("Validation:", X_val.isnull().sum().sum())
print("Test:", X_test.isnull().sum().sum())

"""### 2.9 Feature Engineering"""

# Fix BMI Scale: Divide _BMI5 by 100
for data in [X_train, X_val, X_test]:
    if "_BMI5" in data.columns:
        data["_BMI5"] = data["_BMI5"] / 100

print("BMI scaled by dividing _BMI5 by 100.")


def add_engineered_features(X):
    X = X.copy()

    # Health burden score
    health_cols = [
        col for col in [
            "GENHLTH", "PHYSHLTH", "MENTHLTH", "POORHLTH",
            "DIFFWALK", "DECIDE", "DEAF"
        ]
        if col in X.columns
    ]

    if len(health_cols) > 0:
        X["HEALTH_BURDEN_SCORE"] = X[health_cols].sum(axis=1)

    # Respiratory care / vaccination score
    resp_cols = [
        col for col in [
            "PNEUVAC4", "_PNEUMO3", "FLUSHOT7", "GOT_FLUSHOT"
        ]
        if col in X.columns
    ]

    if len(resp_cols) > 0:
        X["RESP_CARE_SCORE"] = X[resp_cols].sum(axis=1)

    # Smoking score
    smoke_cols = [
        col for col in [
            "SMOKE100", "SMOKDAY2", "_RFSMOK3", "_SMOKER3", "EVER_SMOKED"
        ]
        if col in X.columns
    ]

    if len(smoke_cols) > 0:
        X["SMOKING_SCORE"] = X[smoke_cols].sum(axis=1)

    # Age + BMI interaction
    if "_BMI5" in X.columns and "_AGE80" in X.columns:
        X["BMI_AGE_INTERACTION"] = X["_BMI5"] * X["_AGE80"]

    # Physical limitation interaction
    if "PHYSHLTH" in X.columns and "DIFFWALK" in X.columns:
        X["PHYSICAL_LIMITATION_SCORE"] = X["PHYSHLTH"] * X["DIFFWALK"]

    # General health + checkup
    if "GENHLTH" in X.columns and "RECENT_CHECKUP" in X.columns:
        X["HEALTH_CHECKUP_INTERACTION"] = X["GENHLTH"] * X["RECENT_CHECKUP"]

    # Depression + poor health
    if "HAS_DEPRESSION" in X.columns and "POORHLTH" in X.columns:
        X["DEPRESSION_POOR_HEALTH"] = X["HAS_DEPRESSION"] * X["POORHLTH"]

    # Exercise + BMI
    if "HAS_EXERCISE" in X.columns and "_BMI5" in X.columns:
        X["EXERCISE_BMI_INTERACTION"] = X["HAS_EXERCISE"] * X["_BMI5"]

    return X


X_train = add_engineered_features(X_train)
X_val = add_engineered_features(X_val)
X_test = add_engineered_features(X_test)

print("After feature engineering:")
print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

"""### 2.10 Handling Class Imbalance"""

from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_sample_weight
neg, pos = np.bincount(y_train)

scale_pos_weight = neg / pos

print("Negative class:", neg)
print("Positive class:", pos)
print("scale_pos_weight:", scale_pos_weight)

"""### 2.11 Feature Selection Using XGBoost"""

feature_model = XGBClassifier(
    n_estimators=250,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    min_child_weight=3,
    gamma=0.1,
    objective="binary:logistic",
    eval_metric="logloss",
    tree_method="hist",
    random_state=random_seed,
    n_jobs=2
)

feature_model.fit(X_train, y_train)

feature_importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": feature_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="importance",
    ascending=False
)

print("Top 30 important features:")
print(feature_importance.head(30))

k = 30
selected_features = feature_importance.head(k)["feature"].tolist()

print("\nSelected Top 30 Features:")
print(selected_features)

"""**Feature Importance Plot**"""

drop_redundant = [
    "_SEX",              # keep SEXVAR
    "GOOD_HEALTH",       # keep GENHLTH

    "_BMI5_SCALED",
    "_BMI5CAT",

    "_AGEG5YR",
    "_AGE_G"
]

selected_features = [f for f in selected_features if f not in drop_redundant]
feature_importance = feature_importance[
    feature_importance["feature"].isin(selected_features)
]
plt.figure(figsize=(12, 8))

top_plot = feature_importance

plt.bar(
    top_plot["feature"][::],
    top_plot["importance"][::]
)

plt.ylabel("Importance")
plt.xlabel("Feature")
plt.xticks(rotation=90)
plt.title("Top  Important Features for Asthma Prediction")
plt.tight_layout()
plt.show()

"""**Create Selected Feature Datasets**"""

X_train_sel = X_train[selected_features]
X_val_sel = X_val[selected_features]
X_test_sel = X_test[selected_features]

print("Selected train shape:", X_train_sel.shape)
print("Selected validation shape:", X_val_sel.shape)
print("Selected test shape:", X_test_sel.shape)

"""### 2.12 Feature Scaling"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = X_train_sel.copy()
X_val_scaled = X_val_sel.copy()
X_test_scaled = X_test_sel.copy()

# scale only numeric columns that are actually selected
selected_num_cols = [col for col in num_cols if col in X_train_sel.columns]

print("Numeric columns to scale:")
print(selected_num_cols)

X_train_scaled[selected_num_cols] = scaler.fit_transform(X_train_sel[selected_num_cols])
X_val_scaled[selected_num_cols] = scaler.transform(X_val_sel[selected_num_cols])
X_test_scaled[selected_num_cols] = scaler.transform(X_test_sel[selected_num_cols])

print("Scaling applied only on selected numeric columns.")
print("Scaling applied ONLY on numeric columns.")

"""## 3. Model Training

### 3.1 Threshold Tuning Function
"""

def find_best_threshold(model, X_val_data, y_val):
    val_probs = model.predict_proba(X_val_data)[:, 1]

    best_f1 = 0
    best_threshold = 0.5

    for threshold in np.arange(0.10, 0.90, 0.05):
        val_preds = (val_probs >= threshold).astype(int)
        f1 = f1_score(y_val, val_preds, average="macro")

        if f1 > best_f1:
            best_f1 = f1
            best_threshold = threshold

    return best_threshold, best_f1

"""### 3.2 Create Training Feature Sets"""

train_features = {
    "lr": X_train_scaled,
    "dtc": X_train_sel,
    "rfc": X_train_sel,
    "hgbc": X_train_sel,
    "mlpc": X_train_scaled,
    "xgb": X_train_sel,
    "catboost": X_train_sel,
    "lightgbm": X_train_sel
}

print("Training feature dictionaries created.")

"""### 3.3 Define Models"""

class_counts = np.bincount(y_train)

cat_weights = [
    float(len(y_train) / (2 * class_counts[0])),
    float(len(y_train) / (2 * class_counts[1]))
]


models = {
    "lr": LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        random_state=random_seed
    ),

    "dtc": DecisionTreeClassifier(
        class_weight="balanced",
        random_state=random_seed
    ),

    "rfc": RandomForestClassifier(
        class_weight="balanced",
        random_state=random_seed,
        n_jobs=2
    ),

    "hgbc": HistGradientBoostingClassifier(
        random_state=random_seed
    ),

    "mlpc": MLPClassifier(
        max_iter=200,
        early_stopping=True,
        random_state=random_seed
    ),

    "xgb": XGBClassifier(
        scale_pos_weight=scale_pos_weight,
        objective="binary:logistic",
        eval_metric="logloss",
        tree_method="hist",
        random_state=random_seed,
        n_jobs=2
    ),
    "catboost": CatBoostClassifier(
    loss_function="Logloss",
    random_seed=random_seed,
    verbose=0
    ),

    "lightgbm": LGBMClassifier(
        objective="binary",
        class_weight="balanced",
        random_state=random_seed,
        n_jobs=2
    )
}

"""## 4. Hyperparameter Tuning

### 4.1 Define Parameter Grids
"""

param_grids = {
    "lr": {
        "C": [0.1, 1, 10],
        "tol": [1e-4, 1e-3]
    },

    "dtc": {
        "max_depth": [5, 10, 15],
        "min_samples_split": [2, 5],
        "min_samples_leaf": [1, 5]
    },

    "rfc": {
        "n_estimators": [100, 200],
        "max_depth": [10, 15],
        "min_samples_split": [2, 5],
        "min_samples_leaf": [1, 5]
    },

    "hgbc": {
        "max_iter": [100, 200],
        "learning_rate": [0.05, 0.1],
        "max_leaf_nodes": [15, 31]
    },

    "mlpc": {
        "hidden_layer_sizes": [(64,), (64, 32)],
        "alpha": [0.001, 0.01],
        "learning_rate_init": [0.001]
    },

    "xgb": {
        "n_estimators": [200, 300],
        "max_depth": [3, 4],
        "learning_rate": [0.05],
        "subsample": [0.8],
        "colsample_bytree": [0.8]
    },
    "catboost": {
    "depth": [4, 6],
    "learning_rate": [0.05, 0.1],
    "iterations": [200, 300],
    "class_weights": [cat_weights]
    },

    "lightgbm": {
        "n_estimators": [200, 300],
        "max_depth": [4, 6],
        "learning_rate": [0.05, 0.1],
        "num_leaves": [15, 31]
    }
}

"""### 4.2 Model Name Mapping"""

model_full_names = {
    "lr": "Logistic Regression",
    "dtc": "Decision Tree",
    "rfc": "Random Forest",
    "hgbc": "HistGradientBoosting",
    "mlpc": "MLPClassifier",
    "xgb": "XGBoost",
    "catboost": "CatBoost",
    "lightgbm": "LightGBM"
}

"""### 4.3 Grid Search"""

from sklearn.model_selection import GridSearchCV, PredefinedSplit

val_features = {
    "lr": X_val_scaled,
    "dtc": X_val_sel,
    "rfc": X_val_sel,
    "hgbc": X_val_sel,
    "mlpc": X_val_scaled,
    "xgb": X_val_sel,
    "catboost": X_val_sel,
    "lightgbm": X_val_sel
}

best_models = {}
results = []

for model_name in models.keys():

    print("\n" + "=" * 70)
    print("Grid Search for:", model_full_names[model_name])
    print("=" * 70)

    X_train_val = pd.concat([
        train_features[model_name],
        val_features[model_name]
    ])

    y_train_val = np.concatenate([y_train, y_val])

    split_index = [-1] * len(train_features[model_name]) + [0] * len(val_features[model_name])
    ps = PredefinedSplit(test_fold=split_index)

    grid_search = GridSearchCV(
        estimator=models[model_name],
        param_grid=param_grids[model_name],
        scoring="f1_macro",
        cv=ps,
        n_jobs=2,
        verbose=1,
        return_train_score=True
    )

    grid_search.fit(X_train_val, y_train_val)

    best_models[model_name] = grid_search

    print("Best validation F1-macro:", grid_search.best_score_)
    print("Best parameters:", grid_search.best_params_)
print("Best parameters:", grid_search.best_params_)

"""**GridSearch Summary Table**"""

summary_rows = []

for model_name, grid_search in best_models.items():

    summary_rows.append({
        "Model": model_full_names[model_name],
        "best_score": grid_search.best_score_,
        "best_param": grid_search.best_params_,
        "best_estimator": str(grid_search.best_estimator_).split("(")[0]
    })

summary_df = pd.DataFrame(summary_rows)

summary_df = summary_df.sort_values(
    by="best_score",
    ascending=False
)

pd.set_option("display.max_colwidth", None)

summary_df

"""**Validation/Test data dictionaries**"""

val_features = {
    "lr": X_val_scaled,
    "dtc": X_val_sel,
    "rfc": X_val_sel,
    "hgbc": X_val_sel,
    "mlpc": X_val_scaled,
    "xgb": X_val_sel,
    "catboost": X_val_sel,
    "lightgbm": X_val_sel
}

test_features = {
    "lr": X_test_scaled,
    "dtc": X_test_sel,
    "rfc": X_test_sel,
    "hgbc": X_test_sel,
    "mlpc": X_test_scaled,
    "xgb": X_test_sel,
    "catboost": X_test_sel,
    "lightgbm": X_test_sel
}

"""## 5. Model Evaluation

### 5.1 Final Evaluation on Test Set
"""

from sklearn.base import clone

results = []

for model_name, grid_model in best_models.items():

    print("\n" + "=" * 70)
    print(model_full_names[model_name])
    print("=" * 70)

    model = clone(models[model_name])
    model.set_params(**grid_model.best_params_)

    if model_name in ["lr", "mlpc"]:
        model.fit(X_train_scaled, y_train)
        X_val_current = X_val_scaled
        X_test_current = X_test_scaled
    else:
        model.fit(X_train_sel, y_train)
        X_val_current = X_val_sel
        X_test_current = X_test_sel

    best_threshold, val_f1 = find_best_threshold(
        model,
        X_val_current,
        y_val
    )

    # SAFE probability handling
    if hasattr(model, "predict_proba"):
        test_probs = model.predict_proba(X_test_current)[:, 1]
    else:
        test_probs = model.decision_function(X_test_current)

    test_preds = (test_probs >= best_threshold).astype(int)

    test_accuracy = accuracy_score(y_test, test_preds)
    test_precision = precision_score(y_test, test_preds, zero_division=0)
    test_recall = recall_score(y_test, test_preds, zero_division=0)
    test_f1_macro = f1_score(y_test, test_preds, average="macro")

    results.append({
        "Model": model_full_names[model_name],
        "Best Threshold": best_threshold,
        "Validation F1-macro": val_f1,
        "Test Accuracy": test_accuracy,
        "Test Precision": test_precision,
        "Test Recall": test_recall,
        "Test F1-macro": test_f1_macro
    })

    print("Best parameters:", grid_model.best_params_)
    print("Best threshold:", best_threshold)
    print("Validation F1-macro:", val_f1)
    print("Test F1-macro:", test_f1_macro)

    print("\nClassification Report:")
    print(classification_report(y_test, test_preds, zero_division=0))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, test_preds))

"""**SMOTE Experiment**"""

from imblearn.over_sampling import SMOTE

print("\n" + "=" * 70)
print("Training model: Random Forest + SMOTE")
print("=" * 70)

smote = SMOTE(
    random_state=random_seed,
    k_neighbors=5
)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train_sel,
    y_train
)

print("Before SMOTE:", np.bincount(y_train))
print("After SMOTE:", np.bincount(y_train_smote))

rf_smote = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    random_state=random_seed,
    n_jobs=2
)

rf_smote.fit(X_train_smote, y_train_smote)

best_threshold_smote, val_f1_smote = find_best_threshold(model, X_val_current, y_val)

test_probs_smote = rf_smote.predict_proba(X_test_sel)[:, 1]
test_preds_smote = (test_probs_smote >= best_threshold_smote).astype(int)

results.append({
    "Model": "Random Forest + SMOTE",
    "Best Threshold": best_threshold_smote,
    "Validation F1-macro": val_f1_smote,
    "Test Accuracy": accuracy_score(y_test, test_preds_smote),
    "Test Precision": precision_score(y_test, test_preds_smote, zero_division=0),
    "Test Recall": recall_score(y_test, test_preds_smote, zero_division=0),
    "Test F1-macro": f1_score(y_test, test_preds_smote, average="macro")
})

print("Best Threshold:", best_threshold_smote)
print("Validation F1-macro:", val_f1_smote)
print("Test F1-macro:", f1_score(y_test, test_preds_smote, average="macro"))

print("\nClassification Report:")
print(classification_report(y_test, test_preds_smote, zero_division=0))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, test_preds_smote))

"""### 5.2 Confusion Matrix Visualization"""

import seaborn as sns

# Convert results to dataframe
results_df = pd.DataFrame(results)

# Find best model
best_row = results_df.sort_values("Test F1-macro", ascending=False).iloc[0]

best_model_name = best_row["Model"]
best_threshold = best_row["Best Threshold"]

print("Best model:", best_model_name)

# Find model key
model_key = [k for k, v in model_full_names.items() if v == best_model_name][0]

# Rebuild model
model = clone(models[model_key])
model.set_params(**best_models[model_key].best_params_)

# Use correct data
if model_key in ["lr", "mlpc"]:
    model.fit(X_train_scaled, y_train)
    X_test_current = X_test_scaled
else:
    model.fit(X_train_sel, y_train)
    X_test_current = X_test_sel

# Predict using BEST threshold
test_probs = model.predict_proba(X_test_current)[:, 1]
test_preds = (test_probs >= best_threshold).astype(int)

# Confusion matrix
cm = confusion_matrix(y_test, test_preds)

plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

plt.title(f"Confusion Matrix - {best_model_name}")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""### 5.3 Compare Model Results"""

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Test F1-macro",
    ascending=False
)

print("Final Model Comparison:")
print(results_df)

"""**Model Comparison Plot**"""

# Sort by F1-macro
plot_df = results_df.sort_values(by="Test F1-macro", ascending=False)

plt.figure(figsize=(10, 25))

bars = plt.bar(
    plot_df["Model"],
    plot_df["Test F1-macro"]
)

# Highlight best model
bars[0].set_color("red")

# Add values on top
for i, v in enumerate(plot_df["Test F1-macro"]):
    plt.text(i, v + 0.002, f"{v:.3f}", ha='center')

plt.xticks(rotation=45, ha="right")
plt.ylabel("Test F1-macro")
plt.title("Model Comparison")
plt.ylim(0.58, 0.63)  # zoom into differences

plt.tight_layout()
plt.show()

"""**Save Results**"""

result_dir = abspath_curr + "/result/asthma/"
figure_dir = result_dir + "figure/"

import os

if not os.path.exists(result_dir):
    os.makedirs(result_dir)

if not os.path.exists(figure_dir):
    os.makedirs(figure_dir)

print("Directories ready.")
results_df.to_csv(result_dir + "model_comparison_results.csv", index=False)

summary_df.to_csv(result_dir + "gridsearch_summary.csv", index=False)

selected_features_df = pd.DataFrame({
    "selected_features": selected_features
})

selected_features_df.to_csv(result_dir + "selected_top_features.csv", index=False)

print("Tables saved.")
best_model = best_models["xgb"].best_estimator_

y_pred_test = best_model.predict(X_test_sel)

pd.DataFrame({
    "y_true": y_test,
    "y_pred": y_pred_test
}).to_csv(result_dir + "test_predictions.csv", index=False)

"""## 6. Interpretation

### 6.1 Feature Importance Interpretation

**Plotting the feature importance**
"""

plt.figure(figsize=(12, 8))

top_plot = feature_importance[
    feature_importance["feature"].isin(selected_features)
]

plt.bar(top_plot["feature"], top_plot["importance"])

plt.xticks(rotation=90)
plt.title("Top Important Features")
plt.tight_layout()

plt.savefig(figure_dir + "feature_importance.png", dpi=300)

plt.show()

"""## 7. Conclusion

In this project, several machine learning models were trained and compared for asthma prediction. The data was carefully cleaned, split, imputed, and scaled where needed. Since the dataset was imbalanced, F1-macro was used as the main evaluation metric. The final model was selected based on validation performance and evaluated on the test set.
"""